/*
    Generated by Atomist on 28 06 2016 
*/
package org.sam;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = SamFirstServiceApplication.class)
@WebAppConfiguration
public class SamFirstServiceApplicationTests {

	@Test
	public void contextLoads() {
	}
}
