/*
    Generated by Atomist on 28 06 2016 
*/
package org.sam;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
* Spring Java configuration file for SamFirstService.
* Don't even think of using XML.
*/
@Configuration
public class SamFirstServiceConfiguration {

    // Your beans go here ... 
	// Atomist Bot suggests "maybe use an Atomist project editor to add a sample one?"
}
