/*
    Generated by Atomist on 28 06 2016 
*/
package org.sam;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SamFirstServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(SamFirstServiceApplication.class, args);
    }
}
